### ISSUE TITLE
Treeview doesn't highlight selected item

### ISSUE THREAD

**Issue by Poulpy** [MaxPerl/ttk-Breeze#4]
I'm trying to use the Treeview widget, however I noticed that the background color of the item selected isn't highlighted (in blue). I've only managed to apply those little dots around the item, but that's all.

![image](https://user-images.githubusercontent.com/33195525/77149631-55793e00-6a92-11ea-8db2-a9adaed791ad.png)

Python : 3.5
os : debian

**Comment by Poulpy** [comment]
Woops, wrong repo. Sorry for that :)
https://github.com/TkinterEP/ttkthemes/issues/15

**Comment by MaxPerl** [comment]
Hello,
Could you check, whether https://github.com/MaxPerl/ttk-Breeze/commit/1462e97edca8b2f97a87c61766ab120631ed0693 solves your problem? Thanks, Max

**Comment by Poulpy** [comment]
Wow it works ! Thanks a lot for that, you're a lifesaver :D ! 👍 👍 👍 👍 👍
